app = 'lobsterss'
primary_region = 'lhr'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  min_machines_running = 1
  max_machines_running = 2

  [[http_service.checks]]
    interval = '30s'
    timeout = '3s'
    grace_period = '5s'
    path = '/healthz'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
